version: "3.9"
services:
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_db_data:/data/db
    environment:
      - MONGO_DB_ROOT_USERNAME=root
      - MONGO_DB_ROOT_PASSWORD=password
    restart: "unless-stopped"
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://mongo_db:27017/
volumes:
  mongo_db_data: {}
